name: "Deploy Game"

env:
  GODOT_VERSION: 4.4

on:
  workflow_dispatch:
  push:
    branches:
      - github

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    container:
      image: barichello/godot-ci:4.4
      # https://hub.docker.com/r/barichello/godot-ci/tags
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Mark repository as safe
        run: git config --global --add safe.directory /__w/Bachelor-Thesis/Bachelor-Thesis

      - name: Generate Build Version
        id: version
        shell: bash
        run: |
          BUILD_DATE=$(date +"%Y%m%d")
          BUILD_NUMBER=$(date +"%H%M")
          BUILD_VERSION="v${BUILD_DATE}.${BUILD_NUMBER}"
          echo "build_version=$BUILD_VERSION" >> $GITHUB_OUTPUT
          
          echo "Using build version: $BUILD_VERSION"
          sed -i "s/const VERSION = \".*\"/const VERSION = \"$BUILD_VERSION\"/" src/version_info.gd
          
          echo "Updated version_info.gd:"
          cat src/version_info.gd

      - name: Move export templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/export_templates/4.4.stable ~/.local/share/godot/export_templates/4.4.stable
      
      - name: Create staging directory
        run: mkdir -v -p build/web

      - name: Build
        run: godot -v --export-release --headless "Web" ../build/web/index.html src/project.godot

      - name: Add coi-service-worker
        run: |
          git clone https://github.com/gzuidhof/coi-serviceworker.git
          mv coi-serviceworker/coi-serviceworker.js build/web/coi-serviceworker.js
          sed -i '3 i <script src="coi-serviceworker.js"></script>' build/web/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: "github-ci[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Publish to gh-pages (version ${{ steps.version.outputs.build_version }})"